apiVersion: v1
kind: Secret
metadata:
  name: app-db-secret
  namespace: app
type: Opaque
stringData:
  CONNECTION_STRING: "Server=RDS_ENDPOINT_PLACEHOLDER;Port=3306;Database=DB_NAME_PLACEHOLDER;Uid=DB_USER_PLACEHOLDER;Pwd=DB_PASSWORD_PLACEHOLDER;"