# name: Build and Push ASP.NET Image
# on:
#     push:
#         branches: ['main']
#     workflow_dispatch:
# permissions:
#     id-token: write
#     contents: read

# jobs:
#     buil-and-push:
#         runs-on: ubuntu-latest
#         env:
#             AWS_REGION: us-east-1
#             ECR_REPOSITORY: aspnet-login-app
#             IMAGE_NAME: aspnet-login
#             APP_PATH: app/
#         steps:
#             - name: Checkout repository
#               uses: actions/checkout@v4
#             - name: Configure AWS credentials
#               uses: aws-actions/configure-aws-credentials@v4
#               with:
#                 role-to-assume: arn:aws:iam::336670698191:role/GitHubDeployRole
#                 aws-region: ${{ env.AWS_REGION }}
#             - name: Login to Amazon ECR
#               id: login-ecr
#               uses: aws-actions/amazon-ecr-login@v2
            
#             # 4. Build Docker image
#             - name:  Build Docker image
#               run: |
#                 docker build \
#                 -t $IMAGE_NAME:latest \
#                 -t $IMAGE_NAME:${{ github.sha }} \
#                 $APP_PATH
#             # 5. Tag for ECR
#             - name: Tag image for ECR
#               run: | 
#                 ECR_URL=${{ steps.login-ecr.outputs.repository }}
#                 docker tag $IMAGE_NAME:latest $ECR_URL/$ECR_REPOSITORY:latest
#                 docker tag $IMAGE_NAME:${{ github.sha }} $ECR_URL/ECR_REPOSITORY:${{ github.sha}}
#              # 6. Push image to ECR
#             - name: Push images
#               run: | 
#                 ECR_URL=${{ steps.login-ecr.outputs.repository }}
#                 docker push $ECR_URL/$ECR_REPOSITORY:latest
#                 docker push $ECR_URL/$ECR_REPOSITORY:${{ github.sha }}
#             # 7. Get image digest
#             - name: Export image digest
#               id: digest
#               run: | 
#                 ECR_URL=${{ steps.login-ecr.outputs.repository }}
#                 DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}') "$ECR_URL/$ECR_REPOSITORY:${{ github.sha }}")
#                 echo "digest=$DIGEST" >> $GITHUB_OUTPUT
#                 echo $DIGEST > digest.txt
#             # 8. Save digest to artifact
#             - name: Upload digest artifact
#               uses: actions/upload-artifact@v4
#               with:
#                 name: image-digest
#                 path: digest.txt




