# name: Deploy to EKS
# on:
#     workflow_dispatch:
#     push: 
#         branches: ['main']
#         paths:
#             - "k8s/**"
#             - ".github/workflows/deploy-eks.yml"
# permissions:
#     id-token: write
#     contents: read

# jobs:
#     deploy:
#         name: Deploy application to EKS
#         runs-on: ubuntu-latest
#         env:
#             AWS_REGION: us-east-1
#             EKS_CLUSTER_NAME: # заменить на то что будет создано
#             K8S_NAMESPACE: app
#             DEPLOYMENT_NAME: aspnet-app
#             CONTAINER_NAME: app
#             ECR_REPOSITORY: aspnet-login-app 
#         steps:
#             # 1) Забираем репозиторий (манифесты)
#             - name: Checkout repository
#               uses: actions/checkout@v4
#             # 2) Подключаем AWS по OIDC (без ключей)
#             - name: Configure AWS credentials
#               uses: aws-actions/configure-aws-credentials@v4
#               with:
#                 role-to-assume: arn:aws:iam::336670698191:role/GitHubDeployRole
#                 aws-region: ${{ env.AWS_REGION }}
#             # 3) Забираем digest артефакт из workflow build-and-push.yml
#             - name: Download image digest artifact
#               uses: actions/download-artifact@v4
#               with:
#                 name: image-digest
#                 path: ./.artifact

#             - name: Read image digest
#               id: digest
#               run: |
#                 DIGEST=$(cat ./.artifact/digest.txt | tr -d '\n' | tr -d '\r')
#                 echo "digest=$DIGEST" >> $GITHUB_OUTPUT
#                 echo "Using image digest: $DIGEST"
#             # 4) Устанавливаем kubectl
#             - name: Install kubectl
#               uses: actions/setup-kubectl@v4
#               with:
#                 version: "latest"
#             # 5) Подключаемся к кластеру EKS
#             - name: Update kubeconfig
#               run: | 
#                 aws eks update-kubeconfig \
#                 --name "${{ env.EKS_CLUSTER_NAME }}" \
#                 --region "${{ env.AWS_REGION }}" 
#             # 6) Создаём namespace (идемпотентно)
#             - name: Create namespace if not exists
#               run: | 
#                 kubectl get ns "${{ env.K8S_NAMESPACE }}" || \
#                 kubectl create ns ${{ env.K8S_NAMESPACE }}
#              # 7) Применяем манифесты приложения
#             - name: Apply base k8s manifest
#               run: | 
#                 if [ -d "k8s/app" ]; then
#                   kubectl apply -n "${{ env.K8S_NAMESPACE }}" -f k8s/app
#                 else:
#                   echo "Directory k8s/app not found. Skipping base manifests apply."
#                 fi
#               # 8) Обновляем образ на конкретный digest (самый безопасный способ)
#             - name: Set image to digest and rollout
#               run: | 
#                 IMAGE="${{ steps.digest.outputs.digest }}"
#                 echo "Setting image for ${{ env.DEPLOYMENT_NAME }} container ${{ env.CONTAINER_NAME }} to $IMAGE"
#                 kubectl set image deployment/${{ env.DEPLOYMENT_NAME }} \
#                 ${{ env.CONTAINER_NAME }}=$IMAGE \
#                 -n "${{ env.K8S_NAMESPACE }}"

#                 echo "Waiting for rollout to complete..."
#                 kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }} \
#                 -n "${{ env.K8S_NAMESPACE }}" \
#                 --timeout=120s
#             # 9) Печатаем сервисы/поды для наглядности
#             - name: Show services and pods
#               run: | 
#                 kubectl get svc -n "${{ env.K8S_NAMESPACE }}"
#                 kubectl get pods -o wide "${{ env.K8S_NAMESPACE }}"

                  


      